name: 'Upload Pgyer file Action'
description: 'upload Pgyer file'
author: 'JantHsueh | lumotime'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  url:
    description: 'Web request URL endpoint'
    required: true
  forms:
    description: Data to be transmitted,such as key, pwd, etc. Use json format
    required: false
  fileForms:
    description: Files to be transferred,such as 'file','image' etc. Use json format
    required: false

outputs:
  uploadUrl:
    description: 'upload app action url'
  respCode:
    description: 'upload response code'
  respMessage:
    description: 'upload response message'
  filename:
    description: 'apk filename'
  fileSize:
    description: 'apk file size'
  applicationId: 
    description: 'apk application Id'
  updatedTime:
    description: 'apk upload time'
  invitationQRCode:
    description: 'apk Invitation QR code'

runs:
  using: 'node12'
  main: 'dist/index.js'
